export const EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS";
export const DOCTOR_PROFILE_NOT_VERIFIED = "DOCTOR_PROFILE_NOT_VERIFIED";
export const USER_NOT_FOUND = "USER_NOT_FOUND";
export const SHARING_NOT_ALLOWED = "SHARING_NOT_ALLOWED";
export const SELF_SHARING_NOT_ALLOWED = "SELF_SHARING_NOT_ALLOWED";
export const ALREDAY_SHARED = "ALREDAY_SHARED";
export const USER_ID_REQUIRED = "USER_ID_REQUIRED";